name: flutter_tomtom_navigation_example
description: Demonstrates how to use the flutter_tomtom_navigation plugin.

publish_to: 'none' 

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tomtom_navigation: ^0.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

# While the package is not available on pub.dev, we need an overridden version from Github.
dependency_overrides:
  flutter_tomtom_navigation:
    path: ../
  flutter_tomtom_navigation_android:
    path: ../../flutter_tomtom_navigation_android
  flutter_tomtom_navigation_ios:
    path: ../../flutter_tomtom_navigation_ios
  flutter_tomtom_navigation_platform_interface:
    path: ../../flutter_tomtom_navigation_platform_interface

flutter:
  uses-material-design: true
