name: flutter_tomtom_navigation
description: TomTom Navigation in Flutter using the native iOS and Android SDKs.
version: 0.1.4
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tomtom_navigation_android: ^0.1.4
  flutter_tomtom_navigation_ios: ^0.1.3
  flutter_tomtom_navigation_platform_interface: ^1.0.3

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_tomtom_navigation_android
      ios:
        default_package: flutter_tomtom_navigation_ios
