name: flutter_tomtom_navigation_platform_interface
description: The platform interface for the Flutter TomTom navigation package
version: 1.0.2
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.9
  very_good_analysis: ^5.1.0
